# **IMPORT DATA**

In [1]:
#Import Library
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import PowerTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.feature_extraction.text import CountVectorizer
import re
import nltk.corpus
from sklearn.feature_extraction.text import TfidfVectorizer
import codecs
from sklearn import model_selection
from sklearn.datasets import make_classification
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.metrics import precision_recall_curve, roc_auc_score
from sklearn.metrics import f1_score, roc_curve, auc

# **NBC**

In [9]:
data = pd.read_excel('goto-clean.xlsx')
df=data

In [10]:
text = " ".join(cat.split()[0] for cat in df.tweet)

In [11]:
from sklearn.feature_extraction.text import CountVectorizer
vector = CountVectorizer(min_df=1)
df_counted = vector.fit_transform(df["tweet"])
df_counted = df_counted.toarray()
feature_names = vector.get_feature_names()
feature_counted = pd.DataFrame(df_counted, columns = feature_names)
feature_counted.head()

aamiin  ababil  abalabal  abang  abba  abdl  abimanyu  abin  abis  absen  \
0       0       0         0      0     0     0         0     0     0      0   
1       0       0         0      0     0     0         0     0     0      0   
2       0       0         0      0     0     0         0     0     0      0   
3       0       0         0      0     0     0         0     0     0      0   
4       0       0         0      0     0     0         0     0     0      0   

   ...  yukbismillah  yunki  yurisdiksi  zazkia  zeebo  zero  zeros  zona  \
0  ...             0      0           0       0      0     0      0     0   
1  ...             0      0           0       0      0     0      0     0   
2  ...             0      0           0       0      0     0      0     0   
3  ...             0      0           0       0      0     0      0     0   
4  ...             0      0           0       0      0     0      0     0   

   zonk  zuper  
0     0      0  
1     0      0  
2     0      0  
3     0      0  
4     0      0  

[5 rows x 5846 columns]

In [12]:
#TF-IDF
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer(use_idf = True)
df_tfidf = tfidf_transformer.fit_transform(df_counted)
feature_tfidf = pd.DataFrame(df_tfidf.A, columns =
vector.get_feature_names())
#feature_tfidf.to_excel('tfidf.xlsx')
#print(np.shape(feature_tfidf))
#feature_tfidf

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
#K FOLD
x = feature_tfidf
y = df['sentiment']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1,
random_state = 0)

from sklearn.model_selection import KFold
skf = KFold(n_splits=10, random_state=0, shuffle=True)
skf.get_n_splits(x, y)
i = 1
for train_index, test_index in skf.split(x, y) :
  print("Fold ",i)
  print("TRAIN :",train_index,"TEST :",test_index)
  x_train,x_test=x.loc[train_index] ,x.loc[test_index]
  y_train, y_test=y[train_index], y[test_index]
  i+=1
  modellin = MultinomialNB()
  clf_lin = modellin.fit(x_train, y_train)
  
  probasbaru = [MultinomialNB().fit(x_train, y_train).predict_proba(x_train)]
  print(probasbaru)
    
  pred_labels_tr = modellin.predict(x_train)
  pred_labels_te = modellin.predict(x_test)
  cm_train = confusion_matrix(y_train, pred_labels_tr)
  cm_test = confusion_matrix(y_test, pred_labels_te)
  print('----- Evaluation on Training Data -----')
  score_tr = modellin.score(x_train, y_train)

  print(classification_report(y_train, pred_labels_tr))
  print('--------------------------------------------------------')
  print("Accuracy Train = {:.2f}%".format(score_tr*100))
  print("AUC Train: ", roc_auc_score(y_train, pred_labels_tr))
 
  print("CM Train = ")
  print(cm_train)
  print('----- Evaluation on Test Data -----')
  score_te = modellin.score(x_test, y_test)
  print(classification_report(y_test, pred_labels_te))
  print('--------------------------------------------------------')
  print("Accuracy Test = {:.2f}%".format(score_te*100))
  print("AUC Test: ", roc_auc_score(y_test,pred_labels_te))
  print("CM Test = ")
  print(cm_test)
  print('--------------------------------------------------------')

Fold  1
TRAIN : [   0    1    2 ... 4947 4948 4949] TEST : [  29   31   39   42   44   49   72   98  113  124  125  130  134  138
  142  148  154  158  159  192  202  214  218  241  245  282  291  298
  302  304  308  311  314  333  347  348  349  352  376  380  381  394
  398  402  405  446  452  453  463  470  483  487  489  491  495  499
  500  502  530  531  533  534  541  556  562  567  575  578  582  599
  601  608  619  624  636  639  651  661  675  678  704  716  727  731
  735  751  771  776  780  806  825  831  866  872  873  878  882  883
  896  898  906  910  933  938  939  942  965  976  977  991 1001 1002
 1003 1012 1013 1042 1043 1066 1085 1087 1091 1108 1109 1114 1115 1116
 1118 1141 1176 1185 1202 1220 1239 1245 1246 1250 1262 1271 1275 1338
 1349 1351 1358 1364 1368 1376 1389 1399 1422 1428 1430 1433 1437 1448
 1457 1461 1474 1480 1482 1499 1509 1511 1514 1529 1545 1551 1556 1559
 1564 1586 1606 1632 1642 1643 1651 1662 1670 1680 1688 1691 1695 1696
 1702 1721 1742 17

[array([[0.51369864, 0.48630136],
       [0.33612251, 0.66387749],
       [0.6454615 , 0.3545385 ],
       ...,
       [0.78194134, 0.21805866],
       [0.19591561, 0.80408439],
       [0.84940272, 0.15059728]])]
----- Evaluation on Training Data -----
              precision    recall  f1-score   support

           0       0.94      0.86      0.90      1851
           1       0.91      0.96      0.93      2604

    accuracy                           0.92      4455
   macro avg       0.92      0.91      0.92      4455
weighted avg       0.92      0.92      0.92      4455

--------------------------------------------------------
Accuracy Train = 92.01%
AUC Train:  0.9118812971939442
CM Train = 
[[1598  253]
 [ 103 2501]]
----- Evaluation on Test Data -----
              precision    recall  f1-score   support

           0       0.80      0.67      0.73       192
           1       0.81      0.89      0.85       303

    accuracy                           0.80       495
   macro avg   

              precision    recall  f1-score   support

           0       0.80      0.68      0.73       208
           1       0.79      0.88      0.83       287

    accuracy                           0.79       495
   macro avg       0.80      0.78      0.78       495
weighted avg       0.79      0.79      0.79       495

--------------------------------------------------------
Accuracy Test = 79.39%
AUC Test:  0.7779666979362101
CM Test = 
[[141  67]
 [ 35 252]]
--------------------------------------------------------
Fold  6
TRAIN : [   0    1    2 ... 4947 4948 4949] TEST : [   6    8   11   13   18   20   26   27   41   47   48   52   58   59
   67   80   84   90  107  108  119  145  157  187  194  215  251  254
  268  274  278  303  315  318  328  331  340  344  357  359  360  391
  392  393  438  439  442  455  456  459  468  474  476  477  478  486
  505  518  522  557  563  568  585  588  597  602  603  609  610  646
  653  669  672  676  689  700  715  717  723  752  757  7

[array([[0.51614922, 0.48385078],
       [0.12754836, 0.87245164],
       [0.33561433, 0.66438567],
       ...,
       [0.41391695, 0.58608305],
       [0.75080344, 0.24919656],
       [0.87794507, 0.12205493]])]
----- Evaluation on Training Data -----
              precision    recall  f1-score   support

           0       0.94      0.85      0.89      1844
           1       0.90      0.96      0.93      2611

    accuracy                           0.92      4455
   macro avg       0.92      0.91      0.91      4455
weighted avg       0.92      0.92      0.91      4455

--------------------------------------------------------
Accuracy Train = 91.56%
AUC Train:  0.9064908517360641
CM Train = 
[[1574  270]
 [ 106 2505]]
----- Evaluation on Test Data -----
              precision    recall  f1-score   support

           0       0.84      0.68      0.76       199
           1       0.81      0.92      0.86       296

    accuracy                           0.82       495
   macro avg   

              precision    recall  f1-score   support

           0       0.78      0.70      0.74       211
           1       0.79      0.86      0.82       284

    accuracy                           0.79       495
   macro avg       0.79      0.78      0.78       495
weighted avg       0.79      0.79      0.79       495

--------------------------------------------------------
Accuracy Test = 78.99%
AUC Test:  0.7785278018823845
CM Test = 
[[148  63]
 [ 41 243]]
--------------------------------------------------------


In [15]:
#Klasifikasi Naïve Bayes
x = feature_tfidf
y = df['sentiment']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1,
random_state = 0)
from sklearn.model_selection import KFold
kf = KFold(n_splits=10, random_state=0, shuffle=True)
kf.get_n_splits(x, y)
i = 1
for train_index, test_index in skf.split(x, y) :
  print("Fold ",i)
  print("TRAIN :",train_index,"TEST :",test_index)
  y_train, y_test=y[train_index], y[test_index]
  i+=1
  modellin = MultinomialNB()
  x_train ,x_test=x.loc[train_index] ,x.loc[test_index]
  clf_lin = modellin.fit(x_train, y_train)
  
  pred_labels_tr = modellin.predict(x_train)
  pred_labels_te = modellin.predict(x_test)

  cm_train = confusion_matrix(y_train, pred_labels_tr)
  cm_test = confusion_matrix(y_test, pred_labels_te)

  print('----- Evaluation on Training Data -----')
  score_tr = modellin.score(x_train, y_train)

  print(classification_report(y_train, pred_labels_tr))
  print('--------------------------------------------------------')
  print("Accuracy Train = {:.2f}%".format(score_tr*100))
  print("AUC Train: ", roc_auc_score(y_train, pred_labels_tr))
 
  print("CM Train = ")
  print(cm_train)
  print('----- Evaluation on Test Data -----')
  score_te = modellin.score(x_test, y_test)
  print(classification_report(y_test, pred_labels_te))
  print('--------------------------------------------------------')
  print("Accuracy Test = {:.2f}%".format(score_te*100))
  print("AUC Test: ", roc_auc_score(y_test,pred_labels_te))
  print("CM Test = ")
  print(cm_test)
  print('--------------------------------------------------------')



Fold  1
TRAIN : [   0    1    2 ... 4947 4948 4949] TEST : [  29   31   39   42   44   49   72   98  113  124  125  130  134  138
  142  148  154  158  159  192  202  214  218  241  245  282  291  298
  302  304  308  311  314  333  347  348  349  352  376  380  381  394
  398  402  405  446  452  453  463  470  483  487  489  491  495  499
  500  502  530  531  533  534  541  556  562  567  575  578  582  599
  601  608  619  624  636  639  651  661  675  678  704  716  727  731
  735  751  771  776  780  806  825  831  866  872  873  878  882  883
  896  898  906  910  933  938  939  942  965  976  977  991 1001 1002
 1003 1012 1013 1042 1043 1066 1085 1087 1091 1108 1109 1114 1115 1116
 1118 1141 1176 1185 1202 1220 1239 1245 1246 1250 1262 1271 1275 1338
 1349 1351 1358 1364 1368 1376 1389 1399 1422 1428 1430 1433 1437 1448
 1457 1461 1474 1480 1482 1499 1509 1511 1514 1529 1545 1551 1556 1559
 1564 1586 1606 1632 1642 1643 1651 1662 1670 1680 1688 1691 1695 1696
 1702 1721 1742 17

----- Evaluation on Training Data -----
              precision    recall  f1-score   support

           0       0.94      0.86      0.90      1851
           1       0.91      0.96      0.93      2604

    accuracy                           0.92      4455
   macro avg       0.92      0.91      0.92      4455
weighted avg       0.92      0.92      0.92      4455

--------------------------------------------------------
Accuracy Train = 92.01%
AUC Train:  0.9118812971939442
CM Train = 
[[1598  253]
 [ 103 2501]]
----- Evaluation on Test Data -----
              precision    recall  f1-score   support

           0       0.80      0.67      0.73       192
           1       0.81      0.89      0.85       303

    accuracy                           0.80       495
   macro avg       0.80      0.78      0.79       495
weighted avg       0.80      0.80      0.80       495

--------------------------------------------------------
Accuracy Test = 80.40%
AUC Test:  0.778877887788779
CM Test = 

----- Evaluation on Training Data -----
              precision    recall  f1-score   support

           0       0.94      0.86      0.90      1832
           1       0.91      0.96      0.93      2623

    accuracy                           0.92      4455
   macro avg       0.92      0.91      0.91      4455
weighted avg       0.92      0.92      0.92      4455

--------------------------------------------------------
Accuracy Train = 91.81%
AUC Train:  0.9091886602726637
CM Train = 
[[1574  258]
 [ 107 2516]]
----- Evaluation on Test Data -----
              precision    recall  f1-score   support

           0       0.86      0.64      0.74       211
           1       0.78      0.92      0.84       284

    accuracy                           0.80       495
   macro avg       0.82      0.78      0.79       495
weighted avg       0.81      0.80      0.80       495

--------------------------------------------------------
Accuracy Test = 80.20%
AUC Test:  0.7817819237701088
CM Test =

----- Evaluation on Training Data -----
              precision    recall  f1-score   support

           0       0.94      0.86      0.90      1827
           1       0.91      0.96      0.93      2628

    accuracy                           0.92      4455
   macro avg       0.92      0.91      0.92      4455
weighted avg       0.92      0.92      0.92      4455

--------------------------------------------------------
Accuracy Train = 91.96%
AUC Train:  0.9099495017657512
CM Train = 
[[1564  263]
 [  95 2533]]
----- Evaluation on Test Data -----
              precision    recall  f1-score   support

           0       0.80      0.68      0.73       216
           1       0.78      0.87      0.82       279

    accuracy                           0.79       495
   macro avg       0.79      0.77      0.78       495
weighted avg       0.79      0.79      0.78       495

--------------------------------------------------------
Accuracy Test = 78.59%
AUC Test:  0.7734468339307049
CM Test =